name: Build and Deploy
on:
  push:
    branches:
      - main  # Runs every time you push to main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ› ï¸
        uses: actions/checkout@v4

      - name: Setup Node ğŸŸ¢
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build ğŸ—ï¸
        run: |
          npm install
          npm run build

      - name: Deploy to Branch ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # This takes your 'dist' folder...
          branch: gh-pages # ...and pushes it here!
